version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: apps/dashboard/Dockerfile
    ports:
      - "8001:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - micro-frontend-network

  settings:
    build:
      context: .
      dockerfile: apps/settings/Dockerfile
    ports:
      - "8002:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - micro-frontend-network

  reports:
    build:
      context: .
      dockerfile: apps/reports/Dockerfile
    ports:
      - "8003:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - micro-frontend-network

networks:
  micro-frontend-network:
    driver: bridge
