apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports
  labels:
    app: reports
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
        tier: frontend
    spec:
      containers:
        - name: reports
          image: micro-frontend/reports:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: reports-service
  labels:
    app: reports
spec:
  type: LoadBalancer
  selector:
    app: reports
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
